---
- hosts: centos
  become: true

  tasks:
    - name: Add user ansible
      user:
        name: ansible
        comment: Ansible User
        uid: 454545
        group: wheel
        shell: /bin/bash

    - name: Create a 4096-bit SSH Key for ansible
      user:
        name: ansible
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa

    - name: Add user ansible to sudoers.d
      lineinfile:
        path: /etc/sudoers.d/ansible
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'

    - name: create authorized key file
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
...
