---
- name: Install Apache
  hosts: all
  become: yes

  tasks:
    - name: Install Apache
      yum:
        name:
          - httpd
          - httpd-devel
        state: present

    # - name: Copy Configuration Files
    #   copy:
    #     src: "{{ item.src }}"
    #    httpd-vhosts.conf dest: "{{ item.dest }}"
    #     owner: root
    #     group: root
    #     mode: 0644
    #   with_items:
    #     - src: httpd.conf 
    #       dest: /etc/http/conf/httpd.conf
    #     - src: httpd-vhosts.conf 
    #       dest: /etc/http/conf/

    - name: Ensure Apache is started now and at boot
      service:
        name: httpd
        state: started
        enabled: yes