---
- hosts: centos
  tasks:
    - name: install package if sufficient disk space
      yum:
        name: mariadb-server
        state: latest
      with_items: "{{ ansible_mounts }}"
      when: item.mount == "/" and item.size_available > 10000000000
...
