---
- hosts: centos
  become: true

  tasks:
    - name: install vsftpd
      yum:
        name: vsftpd
        state: present

    - name: enable vsftpd
      service:
        name: vsftpd
        enabled: true

    - name: create readme file
      copy:
        content: "Welcome to my ftp server\n"
        dest: /var/ftp/pub/README
        force: no
        mode: 0444
...