# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  # Application Server 1
  config.vm.define "app1" do |app|
  	app.vm.hostname = "orc-app1.test"
  	app.vm.network :private_network, ip: "192.168.50.4"
  end

    # Application Server 2
  config.vm.define "app2" do |app|
  	app.vm.hostname = "orc-app2.test"
  	app.vm.network :private_network, ip: "192.168.50.5"
  end

    # Database Server
  config.vm.define "db" do |db|
  	db.vm.hostname = "orc-db.test"
  	db.vm.network :private_network, ip: "192.168.50.6"
  end
end