---
- hosts: centos

  tasks:
    - name: Add user nick.oliver
      user:
        name: nick.oliver
        comment: Nick oliver
        uid: 1419
        group: wheel
        shell: /bin/bash

    - name: Create a 4096-bit SSH Key for Nick Oliver
      user:
        name: nick.oliver
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa

    - name: Add user nick.oliver to sudoers.d
      lineinfile:
        path: /etc/sudoers.d/nwoliver
        line: 'nick.oliver ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'

    - name: create authorized key file
      authorized_key:
        user: nick.oliver
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
