Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # Application Server 1
  config.vm.define "solr" do |solr|
  solr.vm.hostname = "ubu-solr.test"
  solr.vm.network :private_network, ip: "192.168.50.4"
  end
end