---
- hosts: centos

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted

  tasks:
    - name: Tell SELinux about SSH's new port.
      seport:
        ports: 2849
        proto: tcp
        setype: ssh_port_t
        state: present

    - name: Make sure SSH is more secure
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: 'sshd -T -f %s'
      with_items:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^Port"
          line: "Port 2849"
      notify: restart sshd

    - name: Install ntp (for time synchronization).
      yum:
        name: ntp
        state: present

    - name: Ensure ntp is running
      service:
        name: ntpd
        state: started
        enabled: yes

    - name: Remove unused packages.
      package:
        name:
          - httpd
          - nano
          - mailutils
        state: absent

    - name: change or modify file permissions.
      file:
        path: /etc/ssh/sshd_config
        mode: 0600

    - name: Set up autoupdates
      yum:
        name: yum-cron
        state: present

    - name: Ensure autoupdates are running
      service:
        name: yum-cron
        state: started
        enabled: yes

    - name: Install firewalld
      package:
        name: firewalld
        state: present

    - name: Ensure that firewalld is running
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Configure ports in firewalld
      firewalld:
        state: "{{ item.state }}"
        port: "{{ item.port }}"
        zone: external
        immediate: yes
        permanent: yes
      with_items:
        - { state: 'enabled', port: 2849/tcp }
        - { state: 'enabled', port: 123/udp }
